name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nolossai:$(date +%s)

# Step 2: Log in to Docker Hub using the secrets you created.
  - name: Log in to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  # Step 3: Build the Docker image.
  # The image name format is <your-docker-hub-username>/<your-repo-name>:<tag>
  - name: Build the Docker image
    run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/nolossaivideo:latest

  # Step 4: Push the built image to Docker Hub.
  - name: Push to Docker Hub
    run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nolossaivideo:latest
